extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  react/react-in-jsx-scope: off
  semi: 2 
env:
  browser: true
settings:
  react:
    pragma: React